### ISSUE TITLE
interfaces/amissl.h:4320:73: error: duplicate ‘const’

### ISSUE THREAD

**Issue by ksdhans** [jens-maus/amissl#62] opened 2022-07-08 04:33 UTC
There's a duplicate const in the OS4 interfaces header, which g++ really doesn't like. It's in the OBSOLEVE_EVP_PBE_scrypt function pointer.

**Comment by Futaura** [comment] 2022-07-08 06:52
This is already fixed in AmiSSL 5.3 (duplicate of #61)

**Closed by Futaura** 2022-07-08 06:52 UTC
Labels: duplicate
