### ISSUE TITLE
OpenSSL 1.1.1

### ISSUE THREAD

**Issue by salass00** [jens-maus/amissl#24] opened 2018-12-17 16:36 UTC
Any plans on updating AmiSSL to OpenSSL 1.1.1a?

After messing around with gcc's build system for the last few days, I finally managed to compile a working gcc 4.0.4 cross compiler from adtools on my Ubuntu PC and then managed to compile some working amissl libraries using it, so I might give this work a try as well.

FWIW I'm mainly interested in having this newer version so that I can add support for ed25519 keys in ssh2-handler.

**Comment by jens-maus** [comment] 2018-12-17 17:01
Feel free to submit a pull request to merge in the OpenSSL 1.1.1 line.

**Comment by sba1** [comment] 2018-12-17 17:09
>After messing around with gcc's build system for the last few days, I
>finally managed to compile a working gcc 4.0.4 cross compiler from
>adtools on my Ubuntu PC and then managed to compile some working amissl
>libraries using it, so I might give this work a try as well.

Please also try gcc 8 because I added baserel support back there. I have not tested it yet apart from minimalistic examples.

**Comment by Futaura** [comment] 2018-12-17 21:47
> After messing around with gcc's build system for the last few days, I finally managed to compile a working gcc 4.0.4 cross compiler from adtools on my Ubuntu PC and then managed to compile some working amissl libraries using it, so I might give this work a try as well.
> Please also try gcc 8 because I added baserel support back there. I have not tested it yet apart from minimalistic examples.

@sba1 I wasn't aware of that - I installed your OS4 native GCC 8 build a while ago, so I'll check the baserel stuff is working

**Comment by salass00** [comment] 2018-12-18 09:15
Attached is a crashlog from running amisslmaster_test with amisslmaster.library compiled using the latest gcc 8.2.0 from adtools.

AFAICT it crashes at LibInit() because of the memset() function (called from InitDebug()) seemingly going into an infinite recursion loop and eventually filling up all of the stack.

[Crashlog_ramlib_2018-12-18_10-43-32.txt](https://github.com/jens-maus/amissl/files/2689679/Crashlog_ramlib_2018-12-18_10-43-32.txt)

**Comment by salass00** [comment] 2018-12-18 09:17
I've also tried with latest gcc 5 and 6 branches and they also seem to have the same problem.

**Comment by jens-maus** [comment] 2018-12-18 09:18
Have fun fixing it. I am unfortunately busy with other projects not having so much (or any) time for Amiga projects anymore.

**Comment by salass00** [comment] 2018-12-18 10:14
Trying to merge in OpenSSL 1.1.1a as described in the README.update-openssl file results in the following error:

$ git subtree pull --prefix openssl --squash https://github.com/openssl/openssl.git OpenSSL_1_1_1a
From https://github.com/openssl/openssl
 * tag                     OpenSSL_1_1_1a -> FETCH_HEAD
fatal: ambiguous argument '3ff855e048b924a2db5133e596da9c25e9aaee27^0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
could not rev-parse split hash 3ff855e048b924a2db5133e596da9c25e9aaee27 from commit d62c916138a4ec9be10f9417f912692727013ee7
Can't squash-merge: 'openssl' was never added.

Any idea what it means?

**Comment by sba1** [comment] 2018-12-21 21:57
> Attached is a crashlog from running amisslmaster_test with amisslmaster.library compiled using the latest gcc 8.2.0 from adtools.
> 
> AFAICT it crashes at LibInit() because of the memset() function (called from InitDebug()) seemingly going into an infinite recursion loop and eventually filling up all of the stack.

Could you possibly provide a minimal example of it and file an adtools Issue? That would help me a lot to fix the problem.

Note that baserel only has been touched in gcc 8.

**Comment by Futaura** [comment] 2018-12-23 23:40
I can confirm the crash in libinit when using the native GCC 8.1.0 also. Will see if I can come up with a minimal example. On the plus side, I can see from the disassembly that it does seem to fix some of the baserel issues that were present after GCC 4.0.4.

**Comment by Futaura** [comment] 2018-12-24 01:06
I should clarify that the only choice for now is to use GCC 4.0.4, not only because of -mbaserel, but -mcheck68kfuncptr also (4.2.4 was the last version to support the latter, but had broken -mbaserel).

**Comment by Futaura** [comment] 2018-12-24 02:18
@sba1 Ok, so baserel is broken in GCC 8. When a baserel_restore function calls __baserel_get_addr(), LR gets trashed. Functions that call this need to also save/restore LR in the prologue/epilogue. This explains the crashes mentioned here - a loop is created as the function never returns, loops back on itself and trashes the stack pointer.

**Comment by Futaura** [comment] 2018-12-24 18:45
I've filed the report, although the memset crash is something else. It happens because -O3 on GCC 5 and up causes a loop in our custom memset to be replaced with a memset call. Solution appears to be to compile with -O2 or use -fno-tree-loop-distribute-patterns.

It's a moot point as we are stuck with GCC 4.0.4 until both baserel and check68kfuncptr are supported.

**Comment by salass00** [comment] 2018-12-24 21:01
In that case adding -fno-builtin-memset when compiling the memset source file should fix the problem.

**Comment by jens-maus** [comment] 2018-12-28 23:05
@all
I just created a new "openssl-1.1.1" branch and merged in the OpenSSL 1.1.1a sources accordingly (see https://github.com/jens-maus/amissl/tree/openssl-1.1.1). I also tried to integrated the first bunch of changes for AmiSSL. However, there is still some way to go until there is a first running AmiSSL 4.x version based on OpenSSL 1.1.1. However, feel free to try yourself to get it compiled and propose any changes via pull request or direct changes to that branch if you want to help out (as my time is quite limited these days).

**Comment by Futaura** [comment] 2018-12-31 16:19
Thanks @jens-maus - I've started work on adapting the required changes (crypto/rand for starters)

**Comment by Futaura** [comment] 2019-01-05 13:17
Quick update from me - managed to get a build of the library that is working with IBrowse, without updating the XML file yet. Seems to work fine on a TLS 1.3 connection to Gmail and doesn't crash, which hopefully means no API function changes. Now going to set about checking that and adding in the new API functions to the XML file (lots to add!).

I've been tearing my hair out trying to figure out how the unified build environment works because there have been quite a few changes to it which are posing big problems to the full AmiSSL build (tools and apps don't build correctly due to wrong compiler options, with no apparent way to fix in the conf file). I've decided to look at that again later as I was getting nowhere fast and would prefer to find a clean solution rather than hack the Configure script, etc.

**Comment by jens-maus** [comment] 2019-01-05 13:43
@Futaura Thanks Oliver for your help in getting AmiSSL ported to use OpenSSL 1.1.1. This already looks quite promising. However, as soon as you have modified the idl (xml) file and integrated all changes from OpenSSL 1.1.0g -> 1.1.1a please let me know so that I can review and test them myself.

Also have a look at the travis build log which should reveal any further issues and which we should try to get to build cleanly again:

https://travis-ci.org/jens-maus/amissl/builds

**Comment by Futaura** [comment] 2019-01-05 14:09
@jens-maus I assume you more or less had to handwrite the XML additions, or did you write a tool? Although not as many as the jump to 1.1.0, there are still 400+ to add. I've fixed up your old checkIDL.sh script which helps, but it might be quicker for me to improve this to fully output the new XML than to do it all by hand :-)

**Comment by jens-maus** [comment] 2019-01-10 09:09
@Futaura Bah, perl... I actually hate perl because it not only suxxs syntax wise but is as much dead fish like AmigaOS is ;-)

However, on top of that please keep in mind that such a tool IMHO cannot work flawlessly and might give the user the impression that all what he had to do is to run it and be fine. However, the API also often changes already existing functions and as such the xml file need to be tuned also for these changes accordingly. Thus, you anyway have to look over ALL changes by hand and adapt the xml file accordingly. Otherwise you will most probably miss some important changes here+there. So, IMHO we would need an additional review of your changes to the xml file before we can actually merge this stuff to the master branch for a subsequent release afterwards.

But don't get me wrong. Many thanks for your changes. This is a big leap forward to get OpenSSL 1.1.1 integrated into AmiSSL. Looking forward to get this finalized soon because I do feel that TLS 1.3 will become pretty much the new main standard retiring the old TLS1 and TLS1.1 all together soon. The only thing I don't know is, if the new ciphers might be too complex for the old 68k hardware so that all the old people still wanting to run this stuff on real 68k hardware might end up in a non-working OpenSSL due to timeouts because the new ciphers might simple cost to much processing time for real 68k hardware (which is fine with me because I do feel that now with 2019 it is time to move on!) :)

So what are your next plans? Are you done with your changes so that I might review them soonish and see if you missed some new functions or changes to old functions? And please have a look at travis as well. It still reports for all Amiga platforms that the openssl-1.1.1 branch doesn't build cleanly (see https://travis-ci.org/jens-maus/amissl/builds/477505197).

**Comment by Futaura** [comment] 2019-01-10 12:08
Yes, understood. That's why I called it a helper tool - it should be used only in conjunction with all the other useful things that you have mentioned in the update README. Of course, I plan to take a detailed look over the API changes next to double-check. I already modified a few of the existing functions (minor changes, like typedef name changes and losing volatile keyword) as compiled the glue files actually flagged changes up.

I still need to check the cert stuff not work, but it looks like I might just be missing some certs as OpenSSL is trying to load them as before, but some files are missing. I did update the certs locally, but perhaps something went wrong there.

I'm well aware the build is 100% working yet as it should - it stops at ../../openssl/apps/ocsp.c:825: error: incompatible type for argument 4 of 'IAmiSSL->BIO_vprintf' as some of the apps have started using that function at we need to adapt them (I've commented them out locally for now, which led to me finding the other issues).  That's the easy part though.  The biggest problem at the moment is changes to the Configure/build environment - the OpenSSL team decided to make at least 9 sets of configurable cflags, but at the same same time removed some of the flexibility that we were relying on. The main two issues being:

1. The apps are now linked against libapps.a. Unfortunately, libapps.a gets built with lib_cflags, whereas those modules need to be built with bin_cflags for us, just as they used to be with previous OpenSSL versions. There appears to be nowhere to adjust this in the build config variables, so the only solution will probably be to modify the Configure script and/or unix makefile script which I'd rather not do, but if it is the only way we need to make it as a small a change as possible.

2. The apps are unnecessarily linked (for AmiSSL) with libssl.a and libcrypto.a - again there is no way for us to override this in our build config, but this might not actually be an issue once 1. is fixed.

My immediate plans are to check over the interface API changes by hand tonight/tomorrow and then they will be ready for you to check.  After that I will look into the build issues again. I have no other changes currently pending at the time of typing this.

**Comment by jerseywurzel** [comment] 2019-01-10 18:49
Hi Jens,

On 10/01/2019, you wrote:
> @Futaura Bah, perl... I actually hate perl because it not only suxxs syntax wise but is as

> But don't get me wrong. Many thanks for your changes. This is a big leap forward to get
> OpenSSL 1.1.1 integrated into AmiSSL. Looking forward to get this finalized soon because I
> do feel that TLS 1.3 will become pretty much the new main standard retiring the old TLS1
> and TLS1.1 all together soon. The only thing I don't know is, if the new ciphers might be
> too complex for the old 68k hardware so that all the old people still wanting to run this
> stuff on real 68k hardware might end up in a non-working OpenSSL due to timeouts because
> the new ciphers might simple cost to much processing time for real 68k hardware (which is
> fine with me because I do feel that now with 2019 it is time to move on!) :)


I still use 68k Amiga and am happy to test for you :)


Bye for now,
-- 
Russell

C makes it easy to shoot yourself in the foot.C++ makes it harder, but when you do, it blows away your whole leg.
-- Bjarne Stroustrup

weather: 
Partly Cloudy : 6.00 C, 42.80 F
Winds : Variable 9.21 MPH, 14.82 KPH, 8.00 Knots
 Jersey Airport (EGJJ), United Kingdom

**Comment by Futaura** [comment] 2019-01-11 10:43
@jens-maus made great progress last night and will have a bunch of changes to commit later today which should resolve most issues.

Quick question: When it come to new stdio (FILE * args) functions in the XML file, should I omit them entirely or define them as unimplemented? I noticed old things like PEM_read/write are missing completely from the XML whereas more recently some stdio functions have been included as unimplemented.

**Comment by jens-maus** [comment] 2019-01-11 11:03
@Futaura Great. Looking forward to review your changes. And indeed, I would add these unsupported "FILE*" function as "unimplemented" rather than omitting them completely.

**Comment by Futaura** [comment] 2019-01-11 11:41
@jens-maus One more slightly more complex query: I had wanted to switch OPENSSL_showfatal() to unimplemented as it is private/internal and breaks compilation of the apps otherwise...

However, it seems this is not possible as it breaks the function offsets and jump tables for non-OS4 targets, due to it being varargs. The sfd is correct, but all generated files from sfdc get broken as there was never an entry allocated for OPENSSL_showfatal before (now it is set as unimplemented, it adds one). Actually, this could be a bug in sfdc?

**Comment by Futaura** [comment] 2019-01-11 22:11
@jens-maus I've committed my next lot of changes. In particular 5bf7c782 fixes the cflags/linklibs problem  with 3 small changes to the config scripts - which will allow things to build correctly as before...

However, there are still some hurdles when it comes to building the app/tests. Some of the new test programs make references to private functions and global variables in libcrypto and libssl, which is obviously a problem for us when linked with AmiSSL.

**Comment by Futaura** [comment] 2019-01-12 19:34
Have to say it has been a bit depressing working on this OpenSSL update. Many compiler warnings due to bad coding and questionable/lazy coding practices. But it is gradually getting there with these as the remaining problematic files:
```openssl/test/asn1_internal_test.c
openssl/test/chacha_internal_test.c
openssl/test/cipher_overhead_test.c
openssl/test/ctype_internal_test.c
openssl/test/curve448_internal_test.c
openssl/test/drbgtest.c
openssl/test/modes_internal_test.c
openssl/test/poly1305_internal_test.c
openssl/test/siphash_internal_test.c
openssl/test/sm2_internal_test.c
openssl/test/sm4_internal_test.c
openssl/test/stack_test.c
openssl/test/tls13encryptiontest.c
openssl/test/wpackettest.c
openssl/test/x509_internal_test.c
```
These tend to avoid the OpenSSL API and make references to functions and variables that are internal.

On the plus side, the AmiSSL libs are working much better now and the cert problem has been fixed. Next I shall investigate an issue that I'm seeing where AmiSSL appears to hang after IBrowse has been idle for a while.

**Comment by Futaura** [comment] 2019-01-16 21:09
@jens-maus So, OS3 and OS4 builds are working on Travis now. However, please can you take a look at  `RSA_X391_derive_ex()` in amissl.xml? The problem is that it takes 13 function parameters which obviously uses up d0-d7 and a0-a3, leaving one more to assign. I've used a4 for now, but maybe a5 would be better?

I think all that is left to do is check over the compiler warnings to check if anything needs fixing. On Friday, I'll also take another look through the diffs to see if there are any new features in OpenSSL that need adapting for AmigaOS.

**Comment by salass00** [comment] 2019-01-27 17:42
Using an AmiSSL built from latest openssl-1.1.1 branch I was able to get ED25519 keys supported in ssh2-handler.

The amissl_v111a_test program crashes on a NULL pointer access in getenv() though:
[Crashlog_amissl_v111a_test_2019-01-27_19-39-44.txt](https://github.com/jens-maus/amissl/files/2800311/Crashlog_amissl_v111a_test_2019-01-27_19-39-44.txt)

**Comment by Futaura** [comment] 2019-01-27 19:00
@salass00 That'll be because the test program was broken - now fixed. Glad to hear it is working for you. Please bear in mind that the updated interface is subject to change until Jens is happy with it.

@jens-maus Please review my changes on this branch, when you get a chance. I think I've done pretty much all that needs doing.

What remains is to review the 'RSA_X391_derive_ex' m68k register usage, update the certs drawer and any other release related changes in docs, etc.

The MorphOS build also needs fixing as the failures on Travis show (looks like an includes issue with some mos network functions getting used in place of the libcmt versions). OS4 and OS3 builds complete successfully.

**Comment by jens-maus** [comment] 2019-02-14 13:18
@Futaura Many thanks Oliver for your hard work. It took me a while but I was able to review your changes and couldn't see any conflicts. Thus, I merged the openssl-1.1.1 branch on master and IMHO we could start preparing a new release. Any objections?

**Comment by Futaura** [comment] 2019-02-14 15:49
@jens-maus Thanks for checking - glad all seems ok (there were many more changes than I had hoped for in a "relatively minor" update apart from TLSv1.3). My only query really is with the 'RSA_X391_derive_ex' register usage for m68k - as I said, I used a4 as the parameter (not sure if this will conflict with the small data pointer in apps, but I guess the compiler should be smart enough to save the register). Likewise, if I used a5, could be an issue with the frame pointer when used. I'll try to test this tonight to make sure.

Other than that, I'm happy for the release to happen. It has been working stable for me in IBrowse.

**Comment by Futaura** [comment] 2019-02-14 19:39
Ok, so I guess 13 parameters is just too long for a m68k library call. SAS/C issues a warning: Too many parameters for library call. For, GCC, inline/macros.h is missing a LP13A4() macro, but even if we add one, I note the other macros that handle A4/A5 parameters save those registers in D7 to restore after the function call. But, of course, this function has 13 parameters and we are already using D7.

Conclusion: forget about it for m68k? It will work fine for OS4 of course. But, probably nobody will be using this function anyway.

**Comment by jens-maus** [comment] 2019-02-15 08:25
@Futaura I also think that we should forget that specific from for m68k, yes. Nobody wants to hear it, but IMHO m68k is really EOL ;-)

The only potentially problematic compiler warnings I can see is for the OS4/ppc build:

```
../../openssl/crypto/blake2/blake2b.c:26: warning: integer constant is too large for 'unsigned long' type
../../openssl/crypto/ec/curve448/curve448.c:30: warning: integer constant is too large for 'long' type
../../openssl/crypto/ec/curve448/curve448_tables.c:448: warning: integer constant is too large for 'long' type
../../openssl/crypto/ec/curve448/f_generic.c:15: warning: integer constant is too large for 'long' type
../../openssl/crypto/sha/keccak1600.c:82: warning: integer constant is too large for 'unsigned long' type
../../openssl/test/asn1_encode_test.c:250: warning: integer constant is too large for 'long' type
```

Do you also see these warnings and perhaps you have some way/idea how to fix them?

Apart from these warnings I don't see any reason why we shouldn't release a new 4.3 version soon. But I would like to fix these warnings, if possible.

**Comment by Futaura** [comment] 2019-02-15 10:30
@jens-maus Yes, I saw them too and after checking the generated .o file, I concluded they were nothing to worry about as the generated data is correct. That and I thought OpenSSL 1.1.1b might be out soon and would fix the warnings anyway, although it looks like they haven't been fixed yet.

See https://github.com/openssl/openssl/issues/7556 for discussion on the issue - there is a fix there too.

**Comment by Futaura** [comment] 2019-02-15 11:10
@jens-maus Also, do you still get mails from the IBrowse beta mailing list? I put up my build of AmiSSL for testing with the latest IB beta and it was reported that YAM now crashes. This looks to be a mismatched InitAmiSSL/CleanupAmiSSL pair in YAM, but wanted to make sure it isn't an AmiSSL issue (same crash as in amissl_test.c which I recently fixed).

**Comment by jens-maus** [comment] 2019-02-15 13:15
@Futaura I saw your change in `amissl_test.c`. But I don't understand why `InitAmiSSLA()` seems to be now mandatory right after `OpenAmiSSL()`. Why is this necessary now because YAM indeed doesn't do that yet (see  https://github.com/jens-maus/yam/blob/master/src/tcp/ssl.c#L1041) and IMHO this would indeed be a problem for backward compatibility.

**Comment by Futaura** [comment] 2019-02-15 14:09
I'm not so sure - it has always been the case (since AmiSSL v3) that you must call `InitAmiSSL()` before using any OpenSSL functions (also, any subtasks must call it too). The developer documentation makes this reasonably clear. Every call to a successful `InitAmiSSL()` must be later paired by a `CleanupAmiSSL()` from the same task.

The reason YAM didn't crash before was down to a bit of luck - the change that breaks it is that `getenv("OPENSSL_CONF)` now happens to be used much earlier on in OpenSSL, and this will of course crash if the task state hasn't been allocated and initialized by `InitAmiSSL()`.

**Comment by jens-maus** [comment] 2019-02-15 14:43
Well, in my understanding InitAmiSSL() should only be required when actually creating the connection since you pass the socket base pointer to it (see 
https://github.com/jens-maus/yam/blob/master/src/tcp/ssl.c#L743-L750). So should YAM then call InitAmiSSL() just for being able to use OpenSSL functions like `ERR_load_BIO_strings()` (see https://github.com/jens-maus/yam/blob/master/src/tcp/ssl.c#L1051). And then it would have to cleanup that dummy init amissl when actually creating the SSL connection?!? This seems strange to me. If `InitAmiSSL()` would really always be required why there is `OpenAmiSSL()` then? And how can I find out if AmiSSL was already initialized using `InitAmiSSL()` so that I can call Cleanup or skip it instead?

**Comment by Futaura** [comment] 2019-02-15 15:45
@jens-maus Looking back at AmiSSL it was basically the same then too. 'InitAmiSSL()' does more than socket initialization, and is required for things like `getenv()` and `localtime()` to function. `OpenAmiSSL()` in v3 replaced the use of `OpenLibrary()` in previous versions and in some ways it would have been cleaner for `OpenAmiSSL()` and `InitAmiSSL()` to have been merged for single threaded cases. However, I guess the whole idea is that only the parent task needs to use 'OpenAmiSSL()' and 'CloseAmiSSL()', whereas subtasks don't need to reopen it and just need to use `InitAmiSSL()` and `CleanupAmiSSL()` instead.

Forgive me, but I do not understand the way YAM works when it comes to connections - in what context are `InitSSLConnections()` and `MakeSecureConnections()` called? On the parent task or subtasks/threads? If you can let me know this, I can give you a better answer to your questions :-)

**Comment by jens-maus** [comment] 2019-02-15 15:50
@Futaura Woo, it has been a while since I designed this stuff. So @tboeckel could probably give a better answer here. But I think I remember that `InitSSLConnections()` is called by the parent thread initializing amissl itself and then each sub thread just calls `MakeSecureConnections()` as soon as it has created a tcp connection so that amissl can actually be prepared to perform the SSL handshake.

**Comment by Futaura** [comment] 2019-02-15 16:54
@jens-maus @tboeckel If so, which I guessed would probably be the case, then it is similar to IBrowse. Put simply, every task that uses OpenSSL functions needs to call `InitAmiSSL()` first. For the parent task, it is quite normal to specify an empty taglist. So, that does need adding to `InitSSLConnections()`. The existing `CleanupAmiSSL()` in `CleanupSSLConnections()` pairs with that (it's current existence is a noop due to the missing `InitAmiSSL()` on that task).

`MakeSSLConnection()` and it's `InitAmiSSL()` can stay as it is, as long as there is a matching `CleanupAmiSSL()` called from the subtask somewhere (https://github.com/jens-maus/yam/blob/bd5894d0dc42b905bfd805d8371588d87207f812/src/tcp/Connection.c#L1328 maybe?).

**Comment by jens-maus** [comment] 2019-02-21 12:25
Ok, I think I will release a new AmiSSL 4.3 shortly. Thus we can close this issue IMHO.

**Closed by jens-maus** 2019-02-21 12:25 UTC
Labels: AmigaOS3, AmigaOS4, enhancement
