### ISSUE TITLE
Enabling TLS v1.3 results in "no shared cipher" error (AmiSSL 4.3)

### ISSUE THREAD

**Issue by ksdhans** [jens-maus/amissl#35] opened 2019-07-19 13:48 UTC
TLS v1.3 support appears to be broken. At least, for servers.

If TLSv1.3 is enabled (for servers), then the connection fails with a "no shared cipher" error. I've had this both with my own code, and with openssl's s_server. You can see it by doing the following:
- Generate a self-signed key
- Start the built-in OpenSSL server:
  openssl s_server -key test.key -cert test.crt -verify 0 -accept 443 -WWW verify depth is 0
- Now try to connect to this server using openssl s_client, or Firefox. It will fail, and the server will print the "no shared cipher" error (NOTE: Odyssey will work, because it doesn't support TLSv1.3, forcing it to use a lower protocol)
- Next, stop the server, and rerun it with TLSv1.2 only:
   openssl s_server -tlsv1_2 -key test.key -cert test.crt -verify 0 -accept 443 -WWW verify depth is 0
- When you try to connect again, then it'll work just fine

**Comment by ksdhans** [comment] 2019-07-20 01:35
Not sure if it's related, but using an elliptic curve server certificate also gives me the "no shared cipher" error. Only RSA certificates work. I can generate the elliptic curve certificate, but can't use it.

**Comment by Futaura** [comment] 2020-01-26 13:46
I couldn't really tell what you were ultimately trying to accomplish, from your comments, but somebody pointed me to your thread on os4coding.net. So, you're using AmiSSL in your ZitaFTP server software.  Did you ever get this working? I'm thinking you perhaps missed a call to set up the ciphers (IIRC, it needs to be done differently for TLSv1.3). And I'm not so sure the OpenSSL s_server command is a good test.

**Comment by ksdhans** [comment] 2020-01-27 05:28
Yes, I'm using AmiSSL in ZitaFTP Server. No, I didn't get it working. Instead I downgraded to TLS 1.2.

The same code works with Cygwin on Windows, so it's *not* a coding error on my part.

**Comment by Futaura** [comment] 2020-01-27 19:32
Ok. Could you let me know the commands that you are using to create test.key and test.crt? I'll then rerun your test here with AmiSSL 4.3 and my current dev build which uses OpenSSL 1.1.1d (4.3 uses 1.1.1a). Could be something that was fixed In OpenSSL - if not, I'll find out what's going wrong.

I only had a quick look, but would I be right in saying that the current ZitaFTP on os4depot is statically linked against OpenSSL 1.1.1c?

**Comment by ksdhans** [comment] 2020-01-28 06:42
Sure, the following generates a key using an elliptic curve cipher:
openssl ecparam -name secp521r1 -genkey -param_enc named_curve -out key.pem
openssl req -new -x509 -key key.pem -out cert.pem -days 730 -subj "/CN=localhost"

NOTE: You may need to add -config to the last line, with an AmiSSL config file because the default installation doesn't come with a config file.

> I only had a quick look, but would I be right in saying that the current ZitaFTP on os4depot is statically linked against OpenSSL 1.1.1c?
Yes and no. The actual FTP server uses AmiSSL, but licensing code relies on libcurl and therefore statically links in OpenSSL (it's a third-party lib that I adapted). 

I'm hoping to build an OpenSSL => AmiSSL stub lib at some point, so that I can remove the redundant OpenSSL. I haven't figured out how to generate that yet...

**Comment by Futaura** [comment] 2020-01-29 15:33
Ok - quick update. I am seeing the problem here too - works ok on Windows, but not in AmiSSL - both are using OpenSSL 1.1.1d, and same cert/key/config files. I've traced the problem and am working on a solution.

**Comment by Futaura** [comment] 2020-01-30 18:25
@ksdhans Took a while to pinpoint the cause, but ultimately it has led to the discovery a baserel related bug in GCC 4.0.4 on OS4. Fortunately, it can be easily worked around, but I've got to check if it gets triggered anywhere else in the OpenSSL code. FYI, your test case works on OS3.

Also, it is bugging me that trying to Ctrl-C s_server triggers a busy loop somewhere, so hope to fix that too. Do you know if there is some other way to tell s_server to exit?

**Comment by ksdhans** [comment] 2020-01-31 04:52
Good to hear that you've found the root cause.

I don't know any other method than Ctrl+C to exist s_server.

**Comment by Futaura** [comment] 2020-02-01 14:13
> I'm hoping to build an OpenSSL => AmiSSL stub lib at some point so that I can remove the redundant OpenSSL. I haven't figured out how to generate that yet...
@ksdhans Is that related to #31? I'd like to move discussion on this to that ticket if it is, as I'm going to close this one soon.

**Closed** 2020-02-02 13:06 UTC
Labels: AmigaOS4, bug

**Comment by ksdhans** [comment] 2020-02-03 05:07
> @ksdhans Is that related to #31? I'd like to move discussion on this to that ticket if it is, as I'm going to close this one soon.

True, they are related, but still slightly different. The solution I'm suggesting there wouldn't help in this case because inline stubs are only of use at compile time. An already compiled library such as libcurl would need stubs in another static library.
